apiVersion: v1
kind: Service
metadata:
  name: nestjs-demo
spec:
  selector:
    app: nestjs-demo
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
      nodePort: 32000
  type: LoadBalancer
